services:

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - ./data/azurite:/data

  #signalr-emulator:
    #container_name: signalr-emulator
    #build:
      #context: ./
      #dockerfile: Dockerfile
    #image: signalr-emulator
    #ports:
      #- "7071:7071"
      #- "8888:8888"
