services:

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    ports:
     - "10000:10000"
     - "10001:10001"
     - "10002:10002"
    volumes:
     - ./data/azurite:/data

  signalr-emulator:
    image: klabbet/signalr-emulator
    ports:
      - "8999:8999"
      - "9001:9001"
